site_name: Hyperledger Cello
repo_name: "hyperledger/cello"
repo_url: "https://github.com/hyperledger/cello"
theme:
  name: "material"
  logo: "images/favicon.png"
  favicon: "images/favicon.png"
  feature:
    tabs: true
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: "light-blue"
      accent: "light-blue"
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: "light-blue"
      accent: "light-blue"
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"
markdown_extensions:
  - admonition
  - codehilite
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.mark
  - pymdownx.critic:
      mode: view
docs_dir: docs
nav:
  - Docs:
      - Overview: index.md
      - Concepts: concepts.md
      - Design:
          - Architecture: design/arch.md
      - Setup:
          - Server: setup/server.md
      - Tutorials:
          - "Lesson 0: Introduction": tutorials/introduction.md
          - "Lesson 1: Prerequisites": tutorials/prerequisites.md
      - Agent:
          - Kubernetes: agents/kubernetes.md
          - Fabric operator: agents/fabric-operator.md
      - Operations:
          - Dashboard:
              - Operator operations: operations/dashboard/operator.md
              - Admin operations: operations/dashboard/admin.md
              - User operations: operations/dashboard/user.md
      - Reference:
          - Configuration:
              - Server Configuration: reference/configuration/server.md
          - Commands:
              - make: reference/commands/make.md
              - cli: reference/commands/cli.md
      - Contribute: contributing.md
  - FAQ:
      - faq.md
  - Release Notes:
      - release_note.md
plugins:
 - search
 - mermaid2
#  - minify:
#      minify_html: true
#  - pdf-export:
#      media_type: print
#      combined: true
#      enabled_if_env: ENABLE_PDF_EXPORT
