name: Cello CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build images
        run: |
          make docker-compose
      - name: Start services
        run: |
          MODE=dev make start
          sleep 10
      - name: Run newman tests
        run: |
          make check-api
      - name: Stop services
        if: always()
        run: |
          MODE=dev make stop
      - name: Clean up
        if: always()
        run: |
          make clean
          docker system prune -f
